(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
TId[{da_,ca_,fa_},{db_,cb_,fb_}]:=TBdeltaDirac[da,db]TBdeltaFund[flavor,fa,fb]TBdeltaFund[color,ca,cb];
T0[{da_,ca_,fa_},{db_,cb_,fb_}]:=TBdeltaDirac[da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb];
\[Gamma]5Tf[{da_,ca_,fa_},{db_,cb_,fb_},f_]:=TBgamma5[da,db]TBT[flavor,f,fa,fb]TBdeltaFund[color,ca,cb];

Tf[{da_,ca_,fa_},{db_,cb_,fb_},f_]:=TBdeltaDirac[da,db]TBT[flavor,f,fa,fb]TBdeltaFund[color,ca,cb];
\[Gamma]5T0[{da_,ca_,fa_},{db_,cb_,fb_}]:=TBgamma5[da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb];
\[Gamma]\[Mu]T0[{da_,ca_,fa_},{db_,cb_,fb_},\[Mu]_]:=TBgamma[\[Mu],da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb];
\[Gamma]\[Mu]\[Gamma]5T0[{da_,ca_,fa_},{db_,cb_,fb_},\[Mu]_]:=Module[{dc},TBgamma[\[Mu],da,dc]TBgamma5[dc,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb]];
\[Gamma]\[Mu]T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},\[Mu]_,a_]:=TBgamma[\[Mu],da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb];
\[Gamma]\[Mu]\[Gamma]5T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},\[Mu]_,a_]:=Module[{dc},TBgamma[\[Mu],da,dc]TBgamma5[dc,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb]];
T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},a_]:=TBdeltaDirac[da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb];
TfTa[{da_,ca_,fa_},{db_,cb_,fb_},f_,a_]:=TBdeltaDirac[da,db]TBT[flavor,f,fa,fb]TBT[color,a,ca,cb]
\[Gamma]5T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},a_]:=TBgamma5[da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb];
\[Gamma]5TfTa[{da_,ca_,fa_},{db_,cb_,fb_},f_,a_]:=TBgamma5[da,db]TBT[flavor,f,fa,fb]TBT[color,a,ca,cb];


(* ::Input::Initialization:: *)
gammai[i_,d1_,d2_]:=TBgamma[i,d1,d2]-TBdeltaLorentz[i,0]TBgamma[0,d1,d2];

\[Gamma]0T0[{da_,ca_,fa_},{db_,cb_,fb_}]:=TBgamma[0,da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb];
\[Gamma]0Tf[{da_,ca_,fa_},{db_,cb_,fb_},f_]:=TBgamma[0,da,db]TBT[flavor,f,fa,fb]TBdeltaFund[color,ca,cb];
\[Gamma]0\[Gamma]5T0[{da_,ca_,fa_},{db_,cb_,fb_}]:=Module[{dc},TBgamma[0,da,dc]TBgamma5[dc,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb]];
\[Gamma]0\[Gamma]5Tf[{da_,ca_,fa_},{db_,cb_,fb_},f_]:=Module[{dc},TBgamma[0,da,dc]TBgamma5[dc,db]TBT[flavor,f,fa,fb]TBdeltaFund[color,ca,cb]];
\[Gamma]0T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},a_]:=TBgamma[0,da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb];
\[Gamma]0\[Gamma]5T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},a_]:=Module[{dc},TBgamma[0,da,dc]TBgamma5[dc,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb]];

\[Gamma]iT0[{da_,ca_,fa_},{db_,cb_,fb_},i_]:=gammai[i,da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb];
\[Gamma]iTf[{da_,ca_,fa_},{db_,cb_,fb_},i_,f_]:=gammai[i,da,db]TBT[flavor,f,fa,fb]TBdeltaFund[color,ca,cb];
\[Gamma]i\[Gamma]5T0[{da_,ca_,fa_},{db_,cb_,fb_},i_]:=Module[{dc},gammai[i,da,dc]TBgamma5[dc,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb]];
\[Gamma]i\[Gamma]5Tf[{da_,ca_,fa_},{db_,cb_,fb_},i_,f_]:=Module[{dc},gammai[i,da,dc]TBgamma5[dc,db]TBT[flavor,f,fa,fb]TBdeltaFund[color,ca,cb]];
\[Gamma]iT0Ta[{da_,ca_,fa_},{db_,cb_,fb_},i_,a_]:=gammai[i,da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb];
\[Gamma]i\[Gamma]5T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},i_,a_]:=Module[{dc},gammai[i,da,dc]TBgamma5[dc,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb]];


(* ::Input::Initialization:: *)
csc[{d1_,c1_,f1_},{d2_,c2_,f2_},{d3_,c3_,f3_},{d4_,c4_,f4_}]:=Module[{a,vi1,vi2,vi3,vi4,di1,di2},
TBepsFund[flavor,f2,f4]TBepsFund[flavor,f1,f3]TBepsFund[color,a,c2,c4]TBepsFund[color,a,c1,c3]
1/4 ((-1)TBdeltaDirac[d1,d2] TBdeltaDirac[d3,d4]
+(-1)TBgamma[vi1,d1,d2]TBgamma[vi1,d3,d4]
+(+1) 1/Sqrt[2] sigma[vi2,vi3,d1,d2] 1/Sqrt[2] sigma[vi2,vi3,d3,d4] 
+(-1) TBgamma[vi4,d1,di1]TBgamma5[di1,d2] TBgamma[vi4,d3,di2]TBgamma5[di2,d4]
+(-1) TBgamma5[d1,d2] TBgamma5[d3,d4]
)
];
