(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
TBAutoDefine["AA"]=True;

TBRequiredGroups["AA"]={{color,SUNfund,Nc}};

TBVertex["AA"]="AA";

TBVertexStructure["AA"]=2Tensor[1,2];

TBInnerProduct["AA"]=2Tensor1[1,2]Tensor2[1,2];

TBComment["AA"]="Gluon propagator basis (Vacuum)";

TBAuthor["AA"]="FR Sattler";

TBUsage["AA"]={"Indices: 
	A: {\!\(\*SubscriptBox[\(p\), \(1\)]\),\[Mu],\!\(\*SubscriptBox[\(a\), \(1\)]\)}
	A: {\!\(\*SubscriptBox[\(p\), \(2\)]\),\[Nu],\!\(\*SubscriptBox[\(a\), \(2\)]\)}
We use the form 
	\[ScriptCapitalL] = (2\[Pi]\!\(\*SuperscriptBox[\()\), \(d\)]\)\[Delta](\!\(\*SubscriptBox[\(p\), \(1\)]\)+\!\(\*SubscriptBox[\(p\), \(2\)]\))\!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\)
The gluon propagator (in vacuum) has only two basis elements,
which given by the splitting into longitudinal and transversal subspaces.
The \!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\) are listed in the following:    ",
TableForm[
{
{"\!\(\*FractionBox[\(1\), \(2\)]\)\!\(\*SubscriptBox[SuperscriptBox[\(\[CapitalPi]\), \(\[Perpendicular]\)], \(\[Mu]\[Nu]\)]\)(\!\(\*SubscriptBox[\(p\), \(2\)]\))\!\(\*SubscriptBox[\(\[Delta]\), \(\*SubscriptBox[\(a\), \(1\)] \*SubscriptBox[\(a\), \(2\)]\)]\)"},
{"\!\(\*FractionBox[\(1\), \(2\)]\)\!\(\*SubscriptBox[SuperscriptBox[\(\[CapitalPi]\), \(\[DoubleVerticalBar]\)], \(\[Mu]\[Nu]\)]\)(\!\(\*SubscriptBox[\(p\), \(2\)]\))\!\(\*SubscriptBox[\(\[Delta]\), \(\*SubscriptBox[\(a\), \(1\)] \*SubscriptBox[\(a\), \(2\)]\)]\)"}
},TableHeadings->{{1,2}, {"Tensor"}},TableSpacing->{3, 3}]
};

TBIndices["AA"]={{p1,mu,a1},{p2,nu,a2}};

TBMomentumConservation["AA"]={p2->-p1};

TBBasis["AA"]={
	1/2 transProj[p2,mu,nu]TBdeltaAdj[color,a1,a2]
	(*T^(1)*),
	
	1/2 longProj[p2,mu,nu]TBdeltaAdj[color,a1,a2]
	(*T^(2)*)
};



