(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
TBAutoDefine["AAAClassTrans"]=True;

TBRequiredGroups["AAAClassTrans"]={{color,SUNfund,Nc}};

TBVertex["AAAClassTrans"]={A,A,A};

TBVertexBasis["AAAClassTrans"]=True;

TBComment["AAAClassTrans"]="Three-gluon vertex basis";

TBAuthor["AAAClassTrans"]="FR Sattler";

TBUsage["AAAClassTrans"]={"Indices: 
	A: {\!\(\*SubscriptBox[\(p\), \(1\)]\),\[Mu],\!\(\*SubscriptBox[\(a\), \(1\)]\)}
	A: {\!\(\*SubscriptBox[\(p\), \(2\)]\),\[Nu],\!\(\*SubscriptBox[\(a\), \(2\)]\)}
	A: {\!\(\*SubscriptBox[\(p\), \(3\)]\),\[Rho],\!\(\*SubscriptBox[\(a\), \(3\)]\)}
This vertex basis only contains the full transverse classical tensor structure.
We use the general form 
	\[ScriptCapitalL] = (2\[Pi]\!\(\*SuperscriptBox[\()\), \(d\)]\)\[Delta](\!\(\*SubscriptBox[\(p\), \(1\)]\)+\!\(\*SubscriptBox[\(p\), \(2\)]\)+\!\(\*SubscriptBox[\(p\), \(3\)]\))\!\(\*SubscriptBox[\(\[CapitalPi]\), \(\[Perpendicular]\)]\)(\!\(\*SubscriptBox[\(p\), \(1\)]\))\!\(\*SubscriptBox[\(\[CapitalPi]\), \(\[Perpendicular]\)]\)(\!\(\*SubscriptBox[\(p\), \(2\)]\))\!\(\*SubscriptBox[\(\[CapitalPi]\), \(\[Perpendicular]\)]\)(\!\(\*SubscriptBox[\(p\), \(3\)]\))\!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\)
and the \!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\) are listed in the following:    ",
TableForm[
{
{"\!\(\*SuperscriptBox[\(f\), \(\*SubscriptBox[\(a\), \(1\)] \*SubscriptBox[\(a\), \(2\)] \*SubscriptBox[\(a\), \(3\)]\)]\)(\!\(\*SubscriptBox[\(\[Delta]\), \(\[Mu]\[Nu]\)]\)(\!\(\*SubscriptBox[\(p\), \(2\)]\)-\!\(\*SubscriptBox[\(p\), \(1\)]\)\!\(\*SubscriptBox[\()\), \(\[Rho]\)]\) + \!\(\*SubscriptBox[\(\[Delta]\), \(\[Mu]\[Rho]\)]\)(\!\(\*SubscriptBox[\(p\), \(1\)]\)-\!\(\*SubscriptBox[\(p\), \(3\)]\)\!\(\*SubscriptBox[\()\), \(\[Nu]\)]\) + \!\(\*SubscriptBox[\(\[Delta]\), \(\[Nu]\[Rho]\)]\)(\!\(\*SubscriptBox[\(p\), \(3\)]\)-\!\(\*SubscriptBox[\(p\), \(2\)]\)\!\(\*SubscriptBox[\()\), \(\[Mu]\)]\))"}
},TableHeadings->{{1}, {"Tensor"}},TableSpacing->{3, 3}]
};

TBIndices["AAAClassTrans"]={{p1,mu,a1},{p2,nu,a2},{p3,rho,a3}};

TBMomentumConservation["AAAClassTrans"]={p3->-p1-p2};

TBBasis["AAAClassTrans"]=I TBF[color,a1,a2,a3] {
transProj[p1,mu,mui]transProj[p2,nu,nui]transProj[p3,rho,rhoi] 
(TBdeltaLorentz[mui,nui]TBvec[p2-p1,rhoi] +TBdeltaLorentz[mui,rhoi] TBvec[p1-p3,nui] +TBdeltaLorentz[nui,rhoi]TBvec[p3-p2,mui])
};

TBCanonicalProduct["AAAClassTrans"]=Tensor1[1,2,3]Tensor2[1,2,3]



