(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
TBAutoDefine["AAAOrtho"]=True;

TBRequiredGroups["AAAOrtho"]={{color,SUNfund,Nc}};

TBVertex["AAAOrtho"]={A,A,A};

TBVertexBasis["AAAOrtho"]=True;

TBComment["AAAOrtho"]="Orthonormal three-gluon vertex basis";

TBAuthor["AAAOrtho"]="FR Sattler";

TBReplacements["AAA"]={};

TBUsage["AAAOrtho"]={"Indices: 
	A: {\!\(\*SubscriptBox[\(p\), \(1\)]\),\[Mu],\!\(\*SubscriptBox[\(a\), \(1\)]\)}
	A: {\!\(\*SubscriptBox[\(p\), \(2\)]\),\[Nu],\!\(\*SubscriptBox[\(a\), \(2\)]\)}
	A: {\!\(\*SubscriptBox[\(p\), \(3\)]\),\[Rho],\!\(\*SubscriptBox[\(a\), \(3\)]\)}
This basis is taken from arXiv:1402.1365[hep-ph]
We use the general form 
	\[ScriptCapitalL] = (2\[Pi]\!\(\*SuperscriptBox[\()\), \(d\)]\)\[Delta](\!\(\*SubscriptBox[\(p\), \(1\)]\)+\!\(\*SubscriptBox[\(p\), \(2\)]\)+\!\(\*SubscriptBox[\(p\), \(3\)]\))\!\(\*SuperscriptBox[\(f\), \(\*SubscriptBox[\(a\), \(1\)] \*SubscriptBox[\(a\), \(2\)] \*SubscriptBox[\(a\), \(3\)]\)]\)\!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\)
and the \!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\) can be found in Appendix A of arXiv:1402.1365[hep-ph].
Note that the first four elements are fully transversal, while the remaining elements have at least partially longitudinal legs."
};

TBIndices["AAAOrtho"]={{p1,mu,a1},{p2,nu,a2},{p3,rho,a3}};

TBMomentumConservation["AAAOrtho"]={p3->-p1-p2};

TBCanonicalProduct["AAAOrtho"]=Tensor1[1,2,3]Tensor2[1,2,3];


(* ::Input::Initialization:: *)
TBBasis["AAAOrtho"]=I TBF[color,a1,a2,a3] Import["./AAAOrtho_construction.m"];



