(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
TBAutoDefine["Acbc"]=True;

TBRequiredGroups["Acbc"]={{color,SUNfund,Nc},{flavor,SUNfund,Nf}};

TBVertex["Acbc"]="A\!\(\*OverscriptBox[\(c\), \(_\)]\)c";

TBVertexStructure["Acbc"]=Tensor[1,2,3];

TBComment["Acbc"]="Ghost-gluon vertex basis";

TBAuthor["Acbc"]="FR Sattler";

TBUsage["Acbc"]={"Indices: 
	A: {\!\(\*SubscriptBox[\(p\), \(1\)]\),\[Mu],\!\(\*SubscriptBox[\(a\), \(1\)]\)}
	\!\(\*OverscriptBox[\(c\), \(_\)]\): {\!\(\*SubscriptBox[\(p\), \(2\)]\),\!\(\*SubscriptBox[\(a\), \(2\)]\)}
	c: {\!\(\*SubscriptBox[\(p\), \(3\)]\),\!\(\*SubscriptBox[\(a\), \(3\)]\)}
We use the general form 
	\[ScriptCapitalL] = (2\[Pi]\!\(\*SuperscriptBox[\()\), \(d\)]\)\[Delta](\!\(\*SubscriptBox[\(p\), \(1\)]\)+\!\(\*SubscriptBox[\(p\), \(2\)]\)+\!\(\*SubscriptBox[\(p\), \(3\)]\))\!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\)
and the \!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\) are listed in the following:    ",
TableForm[
{{"\[ImaginaryI] \!\(\*SuperscriptBox[\(f\), \(\*SubscriptBox[\(a\), \(1\)] \*SubscriptBox[\(a\), \(2\)] \*SubscriptBox[\(a\), \(3\)]\)]\) (\!\(\*SubscriptBox[\(p\), \(2\)]\)\!\(\*SubscriptBox[\()\), \(\[Mu]\)]\)"},
{"\[ImaginaryI] \!\(\*SuperscriptBox[\(f\), \(\*SubscriptBox[\(a\), \(1\)] \*SubscriptBox[\(a\), \(2\)] \*SubscriptBox[\(a\), \(3\)]\)]\) (\!\(\*SubscriptBox[\(p\), \(1\)]\)\!\(\*SubscriptBox[\()\), \(\[Mu]\)]\)"}
},TableHeadings->{{1,2}, {"Tensor"}},TableSpacing->{3, 3}]
};

TBIndices["Acbc"]={{p1,mu,a1},{p2,a2},{p3,a3}};

TBMomentumConservation["Acbc"]={p1->-p2-p3};

TBBasis["Acbc"]={
	I TBF[color,a1,a2,a3] vec[p2,mu] 
	(*T^(1)*),

	I TBF[color,a1,a2,a3] vec[p1,mu] 
	(*T^(2)*)
};

TBInnerProduct["Acbc"]=Tensor1[1,2,3]Tensor2[1,3,2];



