(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
TBAutoDefine["cbc"]=True;

TBRequiredGroups["cbc"]={{color,SUNfund,Nc}};

TBVertex["cbc"]={cb,c};

TBVertexBasis["cbc"]=False;

TBVertexStructure["cbc"]=Tensor[1,2];

TBInnerProduct["cbc"]=Tensor1[1,2]Tensor2[2,1];

TBCanonicalProduct["cbc"]=Tensor1[1,2]Tensor2[2,1];

TBComment["cbc"]="Ghost propagator basis";

TBAuthor["cbc"]="FR Sattler";

TBReplacements["cbc"]={};

TBUsage["cbc"]={"Indices:
	\!\(\*OverscriptBox[\(c\), \(_\)]\): {\!\(\*SubscriptBox[\(p\), \(1\)]\),\!\(\*SubscriptBox[\(c\), \(1\)]\)}
	c: {\!\(\*SubscriptBox[\(p\), \(2\)]\),\!\(\*SubscriptBox[\(c\), \(2\)]\)}
We use the general form 
	\[ScriptCapitalL] = (2\[Pi]\!\(\*SuperscriptBox[\()\), \(d\)]\)\[Delta](\!\(\*SubscriptBox[\(p\), \(1\)]\)+\!\(\*SubscriptBox[\(p\), \(2\)]\))\!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\)
and the \!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\) are listed in the following:    ",
TableForm[
{
{"\!\(\*SubscriptBox[\(\[Delta]\), \(\*SubscriptBox[\(c\), \(1\)] \*SubscriptBox[\(c\), \(2\)]\)]\)"}
},TableHeadings->{{1,2}, {"Tensor"}},TableSpacing->{3, 3}]
};

TBIndices["cbc"]={{p1,c1},{p2,c2}};

TBMomentumConservation["cbc"]={p2->-p1};

TBBasis["cbc"]={
	TBdeltaAdj[color,c1,c2]
};



