(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
TId[{da_,ca_,fa_},{db_,cb_,fb_}]:=TBdeltaDirac[da,db]TBdeltaFund[flavor,fa,fb]TBdeltaFund[color,ca,cb];
T0[{da_,ca_,fa_},{db_,cb_,fb_}]:=TBdeltaDirac[da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb];
\[Gamma]5Tf[{da_,ca_,fa_},{db_,cb_,fb_},f_]:=TBgamma5[da,db]TBT[flavor,f,fa,fb]TBdeltaFund[color,ca,cb];

Tf[{da_,ca_,fa_},{db_,cb_,fb_},f_]:=TBdeltaDirac[da,db]TBT[flavor,f,fa,fb]TBdeltaFund[color,ca,cb];
\[Gamma]5T0[{da_,ca_,fa_},{db_,cb_,fb_}]:=TBgamma5[da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb];
\[Gamma]\[Mu]T0[{da_,ca_,fa_},{db_,cb_,fb_},\[Mu]_]:=TBgamma[\[Mu],da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb];
\[Gamma]\[Mu]\[Gamma]5T0[{da_,ca_,fa_},{db_,cb_,fb_},\[Mu]_]:=Module[{dc},TBgamma[\[Mu],da,dc]TBgamma5[dc,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb]];
\[Gamma]\[Mu]T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},\[Mu]_,a_]:=TBgamma[\[Mu],da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb];
\[Gamma]\[Mu]\[Gamma]5T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},\[Mu]_,a_]:=Module[{dc},TBgamma[\[Mu],da,dc]TBgamma5[dc,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb]];
T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},a_]:=TBdeltaDirac[da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb];
TfTa[{da_,ca_,fa_},{db_,cb_,fb_},f_,a_]:=TBdeltaDirac[da,db]TBT[flavor,f,fa,fb]TBT[color,a,ca,cb]
\[Gamma]5T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},a_]:=TBgamma5[da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb];
\[Gamma]5TfTa[{da_,ca_,fa_},{db_,cb_,fb_},f_,a_]:=TBgamma5[da,db]TBT[flavor,f,fa,fb]TBT[color,a,ca,cb];


(* ::Input::Initialization:: *)
gammai[i_,d1_,d2_]:=TBgamma[i,d1,d2]-TBdeltaLorentz[i,0]TBgamma[0,d1,d2];

\[Gamma]0T0[{da_,ca_,fa_},{db_,cb_,fb_}]:=TBgamma[0,da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb];
\[Gamma]0Tf[{da_,ca_,fa_},{db_,cb_,fb_},f_]:=TBgamma[0,da,db]TBT[flavor,f,fa,fb]TBdeltaFund[color,ca,cb];
\[Gamma]0\[Gamma]5T0[{da_,ca_,fa_},{db_,cb_,fb_}]:=Module[{dc},TBgamma[0,da,dc]TBgamma5[dc,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb]];
\[Gamma]0\[Gamma]5Tf[{da_,ca_,fa_},{db_,cb_,fb_},f_]:=Module[{dc},TBgamma[0,da,dc]TBgamma5[dc,db]TBT[flavor,f,fa,fb]TBdeltaFund[color,ca,cb]];
\[Gamma]0T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},a_]:=TBgamma[0,da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb];
\[Gamma]0\[Gamma]5T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},a_]:=Module[{dc},TBgamma[0,da,dc]TBgamma5[dc,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb]];

\[Gamma]iT0[{da_,ca_,fa_},{db_,cb_,fb_},i_]:=gammai[i,da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb];
\[Gamma]iTf[{da_,ca_,fa_},{db_,cb_,fb_},i_,f_]:=gammai[i,da,db]TBT[flavor,f,fa,fb]TBdeltaFund[color,ca,cb];
\[Gamma]i\[Gamma]5T0[{da_,ca_,fa_},{db_,cb_,fb_},i_]:=Module[{dc},gammai[i,da,dc]TBgamma5[dc,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBdeltaFund[color,ca,cb]];
\[Gamma]i\[Gamma]5Tf[{da_,ca_,fa_},{db_,cb_,fb_},i_,f_]:=Module[{dc},gammai[i,da,dc]TBgamma5[dc,db]TBT[flavor,f,fa,fb]TBdeltaFund[color,ca,cb]];
\[Gamma]iT0Ta[{da_,ca_,fa_},{db_,cb_,fb_},i_,a_]:=gammai[i,da,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb];
\[Gamma]i\[Gamma]5T0Ta[{da_,ca_,fa_},{db_,cb_,fb_},i_,a_]:=Module[{dc},gammai[i,da,dc]TBgamma5[dc,db](TBdeltaFund[flavor,fa,fb]/(Sqrt[2Nf]))TBT[color,a,ca,cb]];


(* ::Input::Initialization:: *)
csc[{d1_,c1_,f1_},{d2_,c2_,f2_},{d3_,c3_,f3_},{d4_,c4_,f4_}]:=Module[{a,vi1,vi2,vi3,vi4,di1,di2},
TBepsFund[flavor,f2,f4]TBepsFund[flavor,f1,f3]TBepsFund[color,a,c2,c4]TBepsFund[color,a,c1,c3]
1/4 1/4 (TBdeltaDirac[d1,d2] TBdeltaDirac[d3,d4]
+TBgamma[vi1,d1,d2]TBgamma[vi1,d3,d4]
-1/Sqrt[2] sigma[vi2,vi3,d1,d2] 1/Sqrt[2] sigma[vi2,vi3,d3,d4] 
- I TBgamma[vi4,d1,di1]TBgamma5[di1,d2] I TBgamma[vi4,d3,di2]TBgamma5[di2,d4]
+ TBgamma5[d1,d2] TBgamma5[d3,d4]
)
];


(* ::Input::Initialization:: *)
TBAutoDefine["FierzCompleteNf2Nc3NJL"]=True;

TBRequiredGroups["FierzCompleteNf2Nc3NJL"]={{color,SUNfund,Nc},{flavor,SUNfund,Nf}};

TBVertex["FierzCompleteNf2Nc3NJL"]={qb,q,qb,q};

TBVertexStructure["FierzCompleteNf2Nc3NJL"]=2Tensor[1,2,3,4]-2Tensor[3,2,1,4];

TBComment["FierzCompleteNf2Nc3NJL"]="Fierz-complete, phenomenologically inspired basis for \!\(\*SubscriptBox[\(N\), \(f\)]\)=2, \!\(\*SubscriptBox[\(N\), \(c\)]\)=3 as given in arXiv:1801.08338.";

TBAuthor["FierzCompleteNf2Nc3NJL"]="Andreas Gei\[SZ]el";

TBReplacements["FierzCompleteNf2Nc3NJL"]={};

TBUsage["FierzCompleteNf2Nc3NJL"]={"Indices: 
	\!\(\*OverscriptBox[\(q\), \(_\)]\): {\!\(\*SubscriptBox[\(p\), \(1\)]\),\!\(\*SubscriptBox[\(d\), \(1\)]\),\!\(\*SubscriptBox[\(A\), \(1\)]\),\!\(\*SubscriptBox[\(F\), \(1\)]\)}
	q: {\!\(\*SubscriptBox[\(p\), \(2\)]\),\!\(\*SubscriptBox[\(d\), \(2\)]\),\!\(\*SubscriptBox[\(A\), \(2\)]\),\!\(\*SubscriptBox[\(F\), \(2\)]\)}
    \!\(\*OverscriptBox[\(q\), \(_\)]\): {\!\(\*SubscriptBox[\(p\), \(3\)]\),\!\(\*SubscriptBox[\(d\), \(3\)]\),\!\(\*SubscriptBox[\(A\), \(3\)]\),\!\(\*SubscriptBox[\(F\), \(3\)]\)}
	q: {\!\(\*SubscriptBox[\(p\), \(4\)]\),\!\(\*SubscriptBox[\(d\), \(4\)]\),\!\(\*SubscriptBox[\(A\), \(4\)]\),\!\(\*SubscriptBox[\(F\), \(4\)]\)}
We suppress the momentum-conservation delta (2\[Pi]\!\(\*SuperscriptBox[\()\), \(d\)]\)\[Delta](\!\(\*SubscriptBox[\(p\), \(1\)]\)+\!\(\*SubscriptBox[\(p\), \(2\)]\)+\!\(\*SubscriptBox[\(p\), \(3\)]\)+\!\(\*SubscriptBox[\(p\), \(4\)]\)).
The implemented tensor strucures correspond to the following channels:    ",
TableForm[
{
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubscriptBox[\((V + A)\), \(\[LeftDoubleBracketingBar]\)]]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(0\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) + (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(i\[Gamma]\), \(0\)]\)\!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubscriptBox[\((V + A)\), \(\[Perpendicular]\)]]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(i\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) + (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(i\[Gamma]\), \(i\)]\)\!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubscriptBox[\((V - A)\), \(\[LeftDoubleBracketingBar]\)]]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(0\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) - (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(i\[Gamma]\), \(0\)]\)\!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubscriptBox[\((V - A)\), \(\[Perpendicular]\)]]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(i\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) - (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(i\[Gamma]\), \(i\)]\)\!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubsuperscriptBox[\((V + A)\), \(\[LeftDoubleBracketingBar]\), \(\[Dagger]\)]]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(0\)]\)\!\(\*SuperscriptBox[\(T\), \(a\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) + (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(i\[Gamma]\), \(0\)]\)\!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(T\), \(a\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubsuperscriptBox[\((V - A)\), \(\[Perpendicular]\), \(\[Dagger]\)]]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(i\)]\)\!\(\*SuperscriptBox[\(T\), \(a\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) - (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(i\[Gamma]\), \(i\)]\)\!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(T\), \(a\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), \((\[Pi] - \[Sigma])\)]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) - (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(T\), \(f\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubscriptBox[\((S + P)\), \(-\)]]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) - (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(T\), \(f\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) + (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(5\(\\\ \)\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) - (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SuperscriptBox[\(T\), \(f\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), \((csc)\)]\)","(\!\(\*SuperscriptBox[\(q\), \(T\)]\) \!\(\*SubscriptBox[\(\[Epsilon]\), \(f\)]\)\!\(\*SubscriptBox[\(\[Epsilon]\), \(a\)]\)\!\(\*SubscriptBox[\(C\[Gamma]\), \(5\)]\) q)(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SubscriptBox[\(C\[Epsilon]\), \(a\)]\)\!\(\*SubscriptBox[\(\[Epsilon]\), \(f\)]\) \!\(\*SuperscriptBox[OverscriptBox[\(q\), \(_\)], \(T\)]\))"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubsuperscriptBox[\((S + P)\), \(-\), \(\[Dagger]\)]]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SuperscriptBox[\(T\), \(a\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) - (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(T\), \(f\)]\)\!\(\*SuperscriptBox[\(T\), \(a\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) + (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(T\), \(a\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\) - (\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SuperscriptBox[\(T\), \(f\)]\)\!\(\*SuperscriptBox[\(T\), \(a\)]\) q\!\(\*SuperscriptBox[\()\), \(2\)]\)"}
},TableHeadings->{{1,2,3,4,5,6,7,8,9,10}, {"Name","Channel"}},TableSpacing->{3, 3}],
"The basis can also be found in arXiv:1801.08338."
};
TBIndices["FierzCompleteNf2Nc3NJL"]={{p1,d1,A1,F1},{p2,d2,A2,F2},{p3,d3,A3,F3},{p4,d4,A4,F4}};

TBMomentumConservation["FierzCompleteNf2Nc3NJL"]={};

TBBasis["FierzCompleteNf2Nc3NJL"]={

\[Gamma]0T0[i1,i2]\[Gamma]0T0[i3,i4]+I \[Gamma]0\[Gamma]5T0[i1,i2]I \[Gamma]0\[Gamma]5T0[i3,i4],
(*Subscript[\[ScriptCapitalL], Subscript[(V+A), \[DoubleVerticalBar]]]*)

\[Gamma]iT0[i1,i2,i]\[Gamma]iT0[i3,i4,i]+I \[Gamma]i\[Gamma]5T0[i1,i2,i]I \[Gamma]i\[Gamma]5T0[i3,i4,i],
(*Subscript[\[ScriptCapitalL], Subscript[(V+A), \[Perpendicular]]]*)

\[Gamma]0T0[i1,i2]\[Gamma]0T0[i3,i4]-I \[Gamma]0\[Gamma]5T0[i1,i2]I \[Gamma]0\[Gamma]5T0[i3,i4],
(*Subscript[\[ScriptCapitalL], Subscript[(V-A), \[DoubleVerticalBar]]]*)

\[Gamma]iT0[i1,i2,i]\[Gamma]iT0[i3,i4,i]-I \[Gamma]i\[Gamma]5T0[i1,i2,i]I \[Gamma]i\[Gamma]5T0[i3,i4,i],
(*Subscript[\[ScriptCapitalL], Subscript[(V-A), \[Perpendicular]]]*)

\[Gamma]0T0Ta[i1,i2,a]\[Gamma]0T0Ta[i3,i4,a]+I \[Gamma]0\[Gamma]5T0Ta[i1,i2,a]I \[Gamma]0\[Gamma]5T0Ta[i3,i4,a],
(*Subscript[\[ScriptCapitalL], Subsuperscript[(V+A), \[DoubleVerticalBar], adj]]*)

\[Gamma]iT0Ta[i1,i2,i,a]\[Gamma]iT0Ta[i3,i4,i,a]-I \[Gamma]i\[Gamma]5T0Ta[i1,i2,i,a]I \[Gamma]i\[Gamma]5T0Ta[i3,i4,i,a],
(*Subscript[\[ScriptCapitalL], Subsuperscript[(V-A), \[Perpendicular], adj]]*)

T0[i1,i2]T0[i3,i4]-\[Gamma]5Tf[i1,i2,f]\[Gamma]5Tf[i3,i4,f],
(*Subscript[\[ScriptCapitalL], (\[Pi]-\[Sigma])]*)

T0[i1,i2]T0[i3,i4]-\[Gamma]5Tf[i1,i2,f]\[Gamma]5Tf[i3,i4,f]+\[Gamma]5T0[i1,i2]\[Gamma]5T0[i3,i4]-Tf[i1,i2,f]Tf[i3,i4,f],
(*Subscript[\[Lambda], Subscript[(S+P), -]]*)

csc[i1,i2,i3,i4],
(*Subscript[\[ScriptCapitalL], (csc)]*)

T0Ta[i1,i2,a]T0Ta[i3,i4,a]-\[Gamma]5TfTa[i1,i2,f,a]\[Gamma]5TfTa[i3,i4,f,a]+\[Gamma]5T0Ta[i1,i2,a]\[Gamma]5T0Ta[i3,i4,a]-TfTa[i1,i2,f,a]TfTa[i3,i4,f,a]
(*Subscript[\[Lambda], Subsuperscript[(S+P), -, adj]]*)

(*Subscript[U, A](1)-invariant*)

}//.Thread[{i1,i2,i3,i4}->Map[#[[2;;]]&,TBIndices["FierzCompleteNf2Nc3NJL"]]];

TBInnerProduct["FierzCompleteNf2Nc3NJL"]=(2Tensor1[1,2,3,4]Tensor2[2,1,4,3]-2Tensor1[1,2,3,4]Tensor2[2,3,4,1]);

TBCanonicalProduct["FierzCompleteNf2Nc3NJL"]=Tensor1[1,2,3,4]Tensor2[2,1,4,3];
