(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
Get["utils/four_fermi_tensors.m"]


(* ::Input::Initialization:: *)
TBAutoDefine["FierzCompleteNf2Nc34D"]=True;

TBRequiredGroups["FierzCompleteNf2Nc34D"]={{color,SUNfund,Nc},{flavor,SUNfund,Nf}};

TBVertex["FierzCompleteNf2Nc34D"]="\!\(\*OverscriptBox[\(q\), \(_\)]\)q\!\(\*OverscriptBox[\(q\), \(_\)]\)q";

TBVertexStructure["FierzCompleteNf2Nc34D"]=2Tensor[1,2,3,4]-2Tensor[3,2,1,4];

TBComment["FierzCompleteNf2Nc34D"]="Fierz-complete, phenomenologically inspired basis for \!\(\*SubscriptBox[\(N\), \(f\)]\)=2, \!\(\*SubscriptBox[\(N\), \(c\)]\)=3";

TBAuthor["FierzCompleteNf2Nc34D"]="FR Sattler";

TBUsage["FierzCompleteNf2Nc34D"]={"Indices: 
	\!\(\*OverscriptBox[\(q\), \(_\)]\): {\!\(\*SubscriptBox[\(p\), \(1\)]\),\!\(\*SubscriptBox[\(d\), \(1\)]\),\!\(\*SubscriptBox[\(A\), \(1\)]\),\!\(\*SubscriptBox[\(F\), \(1\)]\)}
	q: {\!\(\*SubscriptBox[\(p\), \(2\)]\),\!\(\*SubscriptBox[\(d\), \(2\)]\),\!\(\*SubscriptBox[\(A\), \(2\)]\),\!\(\*SubscriptBox[\(F\), \(2\)]\)}
    \!\(\*OverscriptBox[\(q\), \(_\)]\): {\!\(\*SubscriptBox[\(p\), \(3\)]\),\!\(\*SubscriptBox[\(d\), \(3\)]\),\!\(\*SubscriptBox[\(A\), \(3\)]\),\!\(\*SubscriptBox[\(F\), \(3\)]\)}
	q: {\!\(\*SubscriptBox[\(p\), \(4\)]\),\!\(\*SubscriptBox[\(d\), \(4\)]\),\!\(\*SubscriptBox[\(A\), \(4\)]\),\!\(\*SubscriptBox[\(F\), \(4\)]\)}
We suppress the momentum-conservation delta (2\[Pi]\!\(\*SuperscriptBox[\()\), \(d\)]\)\[Delta](\!\(\*SubscriptBox[\(p\), \(1\)]\)+\!\(\*SubscriptBox[\(p\), \(2\)]\)+\!\(\*SubscriptBox[\(p\), \(3\)]\)+\!\(\*SubscriptBox[\(p\), \(4\)]\)).
The implemented tensor strucures correspond to the following channels:    ",
TableForm[
{
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), \((\[Pi] - \[Sigma])\)]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SuperscriptBox[\(T\), \(\(0\)\(\\\ \)\)]\)q\!\(\*SuperscriptBox[\()\), \(2\)]\)-(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(T\), \(F\)]\)q)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), \((\[Eta]')\)]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SuperscriptBox[\(T\), \(\(F\)\(\\\ \)\)]\)q\!\(\*SuperscriptBox[\()\), \(2\)]\)-(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(T\), \(0\)]\)q)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubsuperscriptBox[\((S + P)\), \(-\), \(adj\)]]\)",""},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), \((V - A)\)]\)",""},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), \((V + A)\)]\)",""},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SuperscriptBox[\((V - A)\), \(adj\)]]\)",""},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubscriptBox[\((S + P)\), \(+\)]]\)",""},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubsuperscriptBox[\((S + P)\), \(+\), \(adj\)]]\)",""},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubscriptBox[\((S - P)\), \(-\)]]\)",""},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), SubsuperscriptBox[\((S - P)\), \(-\), \(adj\)]]\)",""}
},TableHeadings->{{1,2,3,4,5,6,7,8,9,10}, {"Name","Channel"}},TableSpacing->{3, 3}]
};

TBIndices["FierzCompleteNf2Nc34D"]={{p1,d1,A1,F1},{p2,d2,A2,F2},{p3,d3,A3,F3},{p4,d4,A4,F4}};

TBMomentumConservation["FierzCompleteNf2Nc34D"]={};

TBBasis["FierzCompleteNf2Nc34D"]={
T0[i1,i2]T0[i3,i4]-\[Gamma]5Tf[i1,i2,f]\[Gamma]5Tf[i3,i4,f]
(*Subscript[\[ScriptCapitalL], (\[Pi]-\[Sigma])]*),

Tf[i1,i2,f]Tf[i3,i4,f]-\[Gamma]5T0[i1,i2]\[Gamma]5T0[i3,i4]
(*Subscript[\[ScriptCapitalL], (\[Eta]')]*),

(* U(1)x SU(2)x SU(2)*)

(*
T0[i1,i2]T0[i3,i4]-\[Gamma]5Tf[i1,i2,f]\[Gamma]5Tf[i3,i4,f]+\[Gamma]5T0[i1,i2]\[Gamma]5T0[i3,i4]-Tf[i1,i2,f]Tf[i3,i4,f]
(*Subscript[\[ScriptCapitalL], Subscript[(S+P), -]]*),*)

T0Ta[i1,i2,a]T0Ta[i3,i4,a]-\[Gamma]5TfTa[i1,i2,f,a]\[Gamma]5TfTa[i3,i4,f,a]+\[Gamma]5T0Ta[i1,i2,a]\[Gamma]5T0Ta[i3,i4,a]-TfTa[i1,i2,f,a]TfTa[i3,i4,f,a]
(*Subscript[\[ScriptCapitalL], Subsuperscript[(S+P), -, adj]]*),

(* Fully U(2)x U(2)*)

(*
T0[i1,i2]T0[i3,i4]-\[Gamma]5Tf[i1,i2,f]\[Gamma]5Tf[i3,i4,f]-\[Gamma]5T0[i1,i2]\[Gamma]5T0[i3,i4]+Tf[i1,i2,f]Tf[i3,i4,f]
(*Subscript[\[ScriptCapitalL], Subscript[(S-P), +]]*),*)

\[Gamma]\[Mu]T0[i1,i2,\[Mu]]\[Gamma]\[Mu]T0[i3,i4,\[Mu]]+\[Gamma]\[Mu]\[Gamma]5T0[i1,i2,\[Mu]]\[Gamma]\[Mu]\[Gamma]5T0[i3,i4,\[Mu]]
(*Subscript[\[ScriptCapitalL], (V-A)]*),

\[Gamma]\[Mu]T0[i1,i2,\[Mu]]\[Gamma]\[Mu]T0[i3,i4,\[Mu]]-\[Gamma]\[Mu]\[Gamma]5T0[i1,i2,\[Mu]]\[Gamma]\[Mu]\[Gamma]5T0[i3,i4,\[Mu]]
(*Subscript[\[ScriptCapitalL], (V+A)]*),

\[Gamma]\[Mu]T0Ta[i1,i2,\[Mu],a]\[Gamma]\[Mu]T0Ta[i3,i4,\[Mu],a]+\[Gamma]\[Mu]\[Gamma]5T0Ta[i1,i2,\[Mu],a]\[Gamma]\[Mu]\[Gamma]5T0Ta[i3,i4,\[Mu],a]
(*Subscript[\[ScriptCapitalL], (V-A)^adj]*),

(* U(1)x SU(2)*)

T0[i1,i2]T0[i3,i4]+\[Gamma]5Tf[i1,i2,f]\[Gamma]5Tf[i3,i4,f]+\[Gamma]5T0[i1,i2]\[Gamma]5T0[i3,i4]+Tf[i1,i2,f]Tf[i3,i4,f]
(*Subscript[\[ScriptCapitalL], Subscript[(S+P), +]]*),

T0Ta[i1,i2,a]T0Ta[i3,i4,a]+\[Gamma]5TfTa[i1,i2,f,a]\[Gamma]5TfTa[i3,i4,f,a]+\[Gamma]5T0Ta[i1,i2,a]\[Gamma]5T0Ta[i3,i4,a]+TfTa[i1,i2,f,a]TfTa[i3,i4,f,a]
(*Subscript[\[ScriptCapitalL], Subsuperscript[(S+P), +, adj]]*),

(* SU(2)*)
T0[i1,i2]T0[i3,i4]+\[Gamma]5Tf[i1,i2,f]\[Gamma]5Tf[i3,i4,f]-\[Gamma]5T0[i1,i2]\[Gamma]5T0[i3,i4]-Tf[i1,i2,f]Tf[i3,i4,f]
(*Subscript[\[ScriptCapitalL], Subscript[(S-P), -]]*),

T0Ta[i1,i2,a]T0Ta[i3,i4,a]+\[Gamma]5TfTa[i1,i2,f,a]\[Gamma]5TfTa[i3,i4,f,a]-\[Gamma]5T0Ta[i1,i2,a]\[Gamma]5T0Ta[i3,i4,a]-TfTa[i1,i2,f,a]TfTa[i3,i4,f,a]
(*Subscript[\[ScriptCapitalL], Subsuperscript[(S-P), -, adj]]*)
}//.Thread[{i1,i2,i3,i4}->Map[#[[2;;]]&,TBIndices["FierzCompleteNf2Nc34D"]]];

TBInnerProduct["FierzCompleteNf2Nc34D"]=(2Tensor1[1,2,3,4]Tensor2[2,1,4,3]-2Tensor1[1,2,3,4]Tensor2[2,3,4,1]);
