(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
Get["utils/four_fermi_tensors.m"]


(* ::Input::Initialization:: *)
TBAutoDefine["FierzCompleteNf2Nc3Pheno"]=True;

TBRequiredGroups["FierzCompleteNf2Nc3Pheno"]={{color,SUNfund,Nc},{flavor,SUNfund,Nf}};

TBVertex["FierzCompleteNf2Nc3Pheno"]={qb,q,qb,q};

TBVertexStructure["FierzCompleteNf2Nc3Pheno"]=2Tensor[1,2,3,4]-2Tensor[3,2,1,4];

TBComment["FierzCompleteNf2Nc3Pheno"]="Fierz-complete, phenomenologically inspired basis for \!\(\*SubscriptBox[\(N\), \(f\)]\)=2, \!\(\*SubscriptBox[\(N\), \(c\)]\)=3";

TBAuthor["FierzCompleteNf2Nc3Pheno"]="FR Sattler";

TBUsage["FierzCompleteNf2Nc3Pheno"]={"Indices: 
	\!\(\*OverscriptBox[\(q\), \(_\)]\): {\!\(\*SubscriptBox[\(p\), \(1\)]\),\!\(\*SubscriptBox[\(d\), \(1\)]\),\!\(\*SubscriptBox[\(A\), \(1\)]\),\!\(\*SubscriptBox[\(F\), \(1\)]\)}
	q: {\!\(\*SubscriptBox[\(p\), \(2\)]\),\!\(\*SubscriptBox[\(d\), \(2\)]\),\!\(\*SubscriptBox[\(A\), \(2\)]\),\!\(\*SubscriptBox[\(F\), \(2\)]\)}
    \!\(\*OverscriptBox[\(q\), \(_\)]\): {\!\(\*SubscriptBox[\(p\), \(3\)]\),\!\(\*SubscriptBox[\(d\), \(3\)]\),\!\(\*SubscriptBox[\(A\), \(3\)]\),\!\(\*SubscriptBox[\(F\), \(3\)]\)}
	q: {\!\(\*SubscriptBox[\(p\), \(4\)]\),\!\(\*SubscriptBox[\(d\), \(4\)]\),\!\(\*SubscriptBox[\(A\), \(4\)]\),\!\(\*SubscriptBox[\(F\), \(4\)]\)}
We suppress the momentum-conservation delta (2\[Pi]\!\(\*SuperscriptBox[\()\), \(d\)]\)\[Delta](\!\(\*SubscriptBox[\(p\), \(1\)]\)+\!\(\*SubscriptBox[\(p\), \(2\)]\)+\!\(\*SubscriptBox[\(p\), \(3\)]\)+\!\(\*SubscriptBox[\(p\), \(4\)]\)).
The implemented tensor strucures correspond to the following channels:    ",
TableForm[
{
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), \((\[Pi] - \[Sigma])\)]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SuperscriptBox[\(T\), \(0\(\\\ \)\)]\)q\!\(\*SuperscriptBox[\()\), \(2\)]\)-(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(T\), \(F\)]\)q)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), \((\[Eta]')\)]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SuperscriptBox[\(T\), \(F\(\\\ \)\)]\)q\!\(\*SuperscriptBox[\()\), \(2\)]\)-(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(T\), \(0\)]\)q)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), \((csc)\)]\)","(\!\(\*SuperscriptBox[\(q\), \(T\)]\)\!\(\*SubscriptBox[\(\[Epsilon]\), \(F\)]\)\!\(\*SuperscriptBox[\(\[Epsilon]\), \(A\(\\\ \)\)]\)\!\(\*SubscriptBox[\(C\[Gamma]\), \(5\)]\)q)(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(C\[Epsilon]\), \(A\(\\\ \)\)]\)\!\(\*SuperscriptBox[SubscriptBox[\(\[Epsilon]\), \(F\)], \(\\\ \)]\)\!\(\*SuperscriptBox[OverscriptBox[\(q\), \(_\)], \(T\)]\))"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), \((\*SubscriptBox[\(\[Omega]\), \(0\)])\)]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(0\)]\)\!\(\*SuperscriptBox[\(T\), \(F\(\\\ \)\)]\)q\!\(\*SuperscriptBox[\()\), \(2\)]\)+(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(0\)]\)\!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(T\), \(F\(\\\ \)\)]\)q\!\(\*SuperscriptBox[\()\), \(2\)]\)"},
{"\!\(\*SubscriptBox[\(\[ScriptCapitalL]\), \((\*SubscriptBox[\(\[Omega]\), \(i\)])\)]\)","(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(i\)]\)\!\(\*SuperscriptBox[\(T\), \(F\(\\\ \)\)]\)q\!\(\*SuperscriptBox[\()\), \(2\)]\)+(\!\(\*OverscriptBox[\(q\), \(_\)]\) \!\(\*SubscriptBox[\(\[Gamma]\), \(i\)]\)\!\(\*SubscriptBox[\(\[Gamma]\), \(5\)]\)\!\(\*SuperscriptBox[\(T\), \(F\(\\\ \)\)]\)q\!\(\*SuperscriptBox[\()\), \(2\)]\)"},
{"",""},
{"",""},
{"",""},
{"",""},
{"",""}
},TableHeadings->{{1,2,3,4,5,6,7,8,9,10}, {"Name","Channel"}},TableSpacing->{3, 3}]
};

TBIndices["FierzCompleteNf2Nc3Pheno"]={{p1,d1,A1,F1},{p2,d2,A2,F2},{p3,d3,A3,F3},{p4,d4,A4,F4}};

TBMomentumConservation["FierzCompleteNf2Nc3Pheno"]={};

TBBasis["FierzCompleteNf2Nc3Pheno"]={
T0[i1,i2]T0[i3,i4]-\[Gamma]5Tf[i1,i2,f]\[Gamma]5Tf[i3,i4,f]
(*Subscript[\[ScriptCapitalL], (\[Pi]-\[Sigma])]*),

Tf[i1,i2,f]Tf[i3,i4,f]-\[Gamma]5T0[i1,i2]\[Gamma]5T0[i3,i4]
(*Subscript[\[ScriptCapitalL], (\[Eta]')]*),

csc[i1,i2,i3,i4]
(*Subscript[\[ScriptCapitalL], (csc)]*),

\[Gamma]0T0[i1,i2]\[Gamma]0T0[i3,i4]
(*Subscript[\[ScriptCapitalL], (Subscript[\[Omega], 0])]*),

\[Gamma]iT0[i1,i2,i]\[Gamma]iT0[i3,i4,i]
(*Subscript[\[ScriptCapitalL], (Subscript[\[Omega], i])]*),

\[Gamma]iT0[i1,i2,i]\[Gamma]iT0[i3,i4,i]-\[Gamma]i\[Gamma]5T0[i1,i2,i]\[Gamma]i\[Gamma]5T0[i3,i4,i]
(*Subscript[\[Lambda], Subscript[(V+A), \[Perpendicular]]]*),

\[Gamma]0T0[i1,i2]\[Gamma]0T0[i3,i4]+\[Gamma]0\[Gamma]5T0[i1,i2]\[Gamma]0\[Gamma]5T0[i3,i4]
(*Subscript[\[Lambda], Subscript[(V-A), \[DoubleVerticalBar]]]*),

\[Gamma]0T0Ta[i1,i2,a]\[Gamma]0T0Ta[i3,i4,a]-\[Gamma]0\[Gamma]5T0Ta[i1,i2,a]\[Gamma]0\[Gamma]5T0Ta[i3,i4,a]
(*Subscript[\[Lambda], Subsuperscript[(V+A), \[DoubleVerticalBar], adj]]*),

\[Gamma]iT0Ta[i1,i2,i,a]\[Gamma]iT0Ta[i3,i4,i,a]+\[Gamma]i\[Gamma]5T0Ta[i1,i2,i,a]\[Gamma]i\[Gamma]5T0Ta[i3,i4,i,a]
(*Subscript[\[Lambda], Subsuperscript[(V-A), \[Perpendicular], adj]]*),

T0Ta[i1,i2,a]T0Ta[i3,i4,a]+\[Gamma]5TfTa[i1,i2,f,a]\[Gamma]5TfTa[i3,i4,f,a]-\[Gamma]5T0Ta[i1,i2,a]\[Gamma]5T0Ta[i3,i4,a]-TfTa[i1,i2,f,a]TfTa[i3,i4,f,a]
(*Subscript[\[Lambda], Subsuperscript[(S-P), -, adj]]*)

(*Subscript[U, A](1)-invariant*)

}//.Thread[{i1,i2,i3,i4}->Map[#[[2;;]]&,TBIndices["FierzCompleteNf2Nc3Pheno"]]];

TBInnerProduct["FierzCompleteNf2Nc3Pheno"]=(2Tensor1[1,2,3,4]Tensor2[2,1,4,3]-2Tensor1[1,2,3,4]Tensor2[2,3,4,1]);
