(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
TBAutoDefine["qbq"]=True;

TBRequiredGroups["qbq"]={{color,SUNfund,Nc},{flavor,SUNfund,Nf}};

TBVertex["qbq"]="qbq";

TBVertexStructure["qbq"]=Tensor[1,2];

TBInnerProduct["qbq"]=Tensor1[1,2]Tensor2[2,1];

TBComment["qbq"]="Quark propagator basis";

TBAuthor["qbq"]="FR Sattler";

TBUsage["qbq"]={"Indices:
	\!\(\*OverscriptBox[\(q\), \(_\)]\): {\!\(\*SubscriptBox[\(p\), \(1\)]\),\!\(\*SubscriptBox[\(d\), \(1\)]\),\!\(\*SubscriptBox[\(A\), \(1\)]\),\!\(\*SubscriptBox[\(F\), \(1\)]\)}
	q: {\!\(\*SubscriptBox[\(p\), \(2\)]\),\!\(\*SubscriptBox[\(d\), \(2\)]\),\!\(\*SubscriptBox[\(A\), \(2\)]\),\!\(\*SubscriptBox[\(F\), \(2\)]\)}
We use the general form 
	\[ScriptCapitalL] = (2\[Pi]\!\(\*SuperscriptBox[\()\), \(d\)]\)\[Delta](\!\(\*SubscriptBox[\(p\), \(1\)]\)+\!\(\*SubscriptBox[\(p\), \(2\)]\))\!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\)
and the \!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\) are listed in the following:    ",
TableForm[
{
{"\!\(\*SubscriptBox[\(\[Delta]\), \(\*SubscriptBox[\(A\), \(1\)] \*SubscriptBox[\(A\), \(2\)]\)]\)\!\(\*SubscriptBox[\(\[Delta]\), \(\*SubscriptBox[\(F\), \(1\)] \*SubscriptBox[\(F\), \(2\)]\)]\)\[ImaginaryI](\!\(\*SubscriptBox[\(\[Gamma]\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\(p\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\()\), \(\*SubscriptBox[\(d\), \(1\)] \*SubscriptBox[\(d\), \(2\)]\)]\)"},
{"\!\(\*SubscriptBox[\(\[Delta]\), \(\*SubscriptBox[\(A\), \(1\)] \*SubscriptBox[\(A\), \(2\)]\)]\)\!\(\*SubscriptBox[\(\[Delta]\), \(\*SubscriptBox[\(F\), \(1\)] \*SubscriptBox[\(F\), \(2\)]\)]\)\!\(\*SubscriptBox[\(\[Delta]\), \(\*SubscriptBox[\(d\), \(1\)] \*SubscriptBox[\(d\), \(2\)]\)]\)"}
},TableHeadings->{{1,2}, {"Tensor"}},TableSpacing->{3, 3}]
};

TBIndices["qbq"]={{p1,d1,A1,F1},{p2,d2,A2,F2}};

TBMomentumConservation["qbq"]={p2->-p1};

TBBasis["qbq"]={
	TBdeltaFund[color,A1,A2]TBdeltaFund[flavor,F1,F2]( I pdash[p1,d1,d2] ),
	(*T^(1)*)

	TBdeltaFund[color,A1,A2]TBdeltaFund[flavor,F1,F2](TBdeltaDirac[d1,d2])
	(*T^(2)*)
};



